fractions: main.cpp fraction.cpp
	g++ -Wall -Wextra -Werror -pedantic -pedantic-errors -O2 -march=native -mtune=native -fsanitize=address -fsanitize=undefined -std=c++20 main.cpp -o fractions

clean:
	rm -rf *.o fractions
